name: Extract Secrets
on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Extract
        run: |
          echo "B64_PAGE_ID=$(echo -n '${{ secrets.FB_PAGE_ID }}' | base64)"
          echo "B64_TOKEN=$(echo -n '${{ secrets.FB_ACCESS_TOKEN }}' | base64)"
